ansible_connection: "ssh"
ansible_become: true
ansible_become_method: "sudo"
ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"  # Используем конструкцию с lookup, так как ~ здесь не работает
